### ISSUE TITLE
Recipe Editor

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale-ui#11]
Some considerations for the recipe editor:
- List the actual recipe input values (properties and files) on the recipe detail page (same as inputs on the job detail page).
- Move the recipe editor trigger information to a table above the recipe graph, instead of its current location in the root node. Also move the recipe type inputs to the same table.
- Add ability to reprocess a recipe to the UI

**Comment by ericsvendsen** [comment]
Post the current recipe's revision type to the validate endpoint. That will return a `diff` object with information about what can/will be reprocessed.
