### ISSUE TITLE
Docs in 7.0 don't work

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#123]
Permission denied error when trying to view docs in new ui.

**Comment by ericsvendsen-mil** [comment]
This is most likely due to an incorrect value specified in the runtime config for the `documentation` property. As a result this can be fixed where it is currently deployed.

**Comment by emimaesmith** [comment]
I also didn't build the docs when I deployed Scale the last few times because it was taking 10+ minutes to run the build. Taking out building the docs dropped the build time in half.
