### ISSUE TITLE
Timeline view changes

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#126]
Global:
Support as many items as user picks.
Should be able to toggle between "current" (only active) and "historical" (all) modes
Should be able to toggle between "group versions" or "individual versions" mode
User should only pick job/recipe by name, not specific version
The timeline should be able to pick start and stop times.

In Recipe mode: 
Each "job" should get a separate line and color under the main "bar".

Question: Does timeline support "gaps" or the correct end-date?  
Startdate always looked right, but everything always continued un-interrupted straight through to now() in every example I could find in DEV.

**Comment by ericsvendsen-mil** [comment]
This component visualizes created/deprecated dates for versions of job types or revisions of recipes. If `deprecated` is null, then it uses the current datetime. Date controls don't make sense in this context, and neither does individual bars for jobs inside a recipe. We'll need to better define this component before anything further is done.

**Comment by ericsvendsen-mil** [comment]
Needs further discussion and clarification

**Comment by Rachel-ais** [comment]
Here is a Gantt Chart we might want to use for the changes: http://bl.ocks.org/dk8996/5449641

**Comment by ericsvendsen-mil** [comment]
Ok, so here are the details of what Chris wants to see for the timeline:

* Select the recipe types or job types that will be visualized
* Select a date range
* Chart the days represented by the date range and indicate whether each recipe type ran on that day, or whether each job type had executions run on that day

Somewhere there exists a query that Clint wrote (I think Mike was working on creating an API endpoint) which will return the number of times a particular recipe type or job execution has run for a specified time period, binned by day. So if a recipe type was run 1 or more times, there should be a gantt bar present for that day. If a recipe type was run 0 times, that day should be blank. The chart doesn't need to visualize how many times a recipe type ran - it's an all or nothing situation.

Both job types and recipe types should show relevant revisions in the chart. They can be obtained via the following endpoints:
* http://ngageoint.github.io/scale/docs/rest/v6/recipe_type.html#v6-recipe-type-revisions
* http://ngageoint.github.io/scale/docs/rest/v6/job_type.html#v6-job-type-revisions

**Comment by Rachel-ais** [comment]
@cshamis 

I have some Mock ups for the timeline changes. 

Here would be where you can pick the recipe and revisions and now the Daterange
![Screen Shot 2020-03-02 at 1 18 38 PM](https://user-images.githubusercontent.com/48250701/75704999-69e2cb80-5c88-11ea-968a-e067a05e15a1.png)

Here is a rough mock up of the graph where it is simply blue if the recipe rev ran that day. I know the dates at the bottom look rough but we are hoping to fix those in the actual finished version.
![Screen Shot 2020-03-02 at 12 44 20 PM](https://user-images.githubusercontent.com/48250701/75705001-6c452580-5c88-11ea-8264-a7899564bc56.png)

If this is the right idea I can move forward with development.

**Comment by cshamis** [comment]
YES!!!!!  THAT'S IT EXACTLY!

Bonus points:

Different colors for different recipes but same color for revisions within
that recipe.
Export to high-quality PNG and/or permalink URL.

Question:

It does also work with picking jobs from the job-list as well?

**Comment by mheppner** [comment]
> Export to high-quality PNG and/or permalink URL.
This will be a separate feature, since it's a greater scope of work for this issue.

**Comment by Rachel-ais** [comment]
I'll get the main feature done first then we can talk about the two new issues but yes it will work with job types as well
