### ISSUE TITLE
Scale UI Requires 2 Silo URL environment variables

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#131]
The scale-ui service currently takes two silo url environment variables and only one is set correctly.  We should fix to only require one and set it correctly.

**Comment by emimaesmith** [comment]
@ericsvendsen Any reason why there are two Silo environment variables? Is it possible to consolidate into one?

**Comment by ericsvendsen-mil** [comment]
I'm not sure I understand. There's only the `siloUrl` setting...

**Comment by ericsvendsen-mil** [comment]
To clarify, apparently this is referring to the DCOS environment. @gisjedi would best be able to answer this.

**Comment by gisjedi** [comment]
So this mess is all a result of the need to avoid issues with CORS when making requests to the backend API services from the UI. 

There are 2 settings to allow configurability from both the UI -> Endpoint and Endpoint -> Backend Service. I can see how this is easily confusing and if the default is always used, it really serves no purpose.

`SILO_URL` is used to allow both a relative address (default value `/silo`) or an absolute address (`https://silo.somewhere.com`).
`SILO_BACKEND` is only used internally by Nginx to know where to proxy incoming requests to `/silo`

**Comment by gisjedi** [comment]
It should also be noted that _none_ of these values are required. There are defaults for all of them that will work in most common situations.

**Comment by gisjedi** [comment]
Documentation can be found here: https://github.com/ngageoint/scale-ui/blob/master/docker/README.md
