### ISSUE TITLE
Add Vault Status to Overview

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#132]
Add the Vault status info from issue #1359 to the Scale overview page

**Comment by emimaesmith** [comment]
The vault status was added to the status API in https://github.com/ngageoint/scale/issues/1359. This information may now be utilized in the UI.

**Comment by ericsvendsen-mil** [comment]
This will be added to the UI as described in #124

**Comment by ericsvendsen-mil** [comment]
Closing in favor of #50
