### ISSUE TITLE
Download link for job execution logs

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#133]
Viewing job execution logs in the browser is difficult. It would be helpful to instead have a link that downloads the log as a text file.

**Comment by emimaesmith** [comment]
The new Scale 7.x+ UI has a copy log button. Is it possible to add a download button or is copy sufficient?

**Comment by ericsvendsen-mil** [comment]
I remember talking to Chris about this earlier in the year, and at the time he said the copy button is sufficient. We should check with him to make sure, but I don't think a download link is necessary.

**Comment by ericsvendsen-mil** [comment]
Copying is good enough
