### ISSUE TITLE
Identical jobs in recipe

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale-ui#140]
The canvas that contains the recipe graph does not properly render a recipe that has multiple nodes of the same type.  A good example is the Casino recipe: 
![Screenshot 2019-06-22 14 36 26](https://user-images.githubusercontent.com/22593495/59969881-f7312600-9526-11e9-8c9d-fc40abeb0da8.png)

**Comment by ericsvendsen-mil** [comment]
The editor was never built to handle recipe types like that because it was my understanding that a definition that has multiple nodes of the same type is invalid.

**Comment by ericsvendsen-mil** [comment]
Didn't actually intend to close this earlier. Reopening so we can investigate whether recipes of this type should be supported.

**Comment by Rachel-ais** [comment]
We decided we will support this and it is needed for 7.0.1
