### ISSUE TITLE
Configuration drop downs when editing a pre-exisiting job type

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#143]
Steps to reproduce:

select an existing job type.  
click edit
click on the (2) Configuration page,
try to change the drop downs for workspaces.

**Comment by Rachel-ais** [comment]
I am seeing more issues specifically when configuration is selected while editing. It stops you from being able to use the Navigation bar with the error: "Cannot read property 'files' of undefined". 

Also when selecting configuration it doesn't turn the numbered circle blue. Here Seed Image is selected and the icon is blue 
![Screen Shot 2019-06-24 at 2 28 59 PM](https://user-images.githubusercontent.com/48250701/60042805-8e63be00-968c-11e9-8f95-6fab636b2e30.png)

Here configuration is selected but the seed icon is still blue. 
![Screen Shot 2019-06-24 at 2 29 09 PM](https://user-images.githubusercontent.com/48250701/60042829-99b6e980-968c-11e9-99ce-751671a44c1f.png)

Both issues are giving the error: "Cannot read property 'files' of undefined" in the console when selecting anything on the Nav bar or clicking on the configuration tab so I am assuming they are related to the same bug.

This might need to be a separate issue.

**Comment by ericsvendsen-mil** [comment]
Closing this. I'm tracking all job type editing issues in #128, and I've moved these comments to that issue thread.
