### ISSUE TITLE
Input label/defaults changes

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#160]
When going through the UI today there were a few places where the label for an input was not accurate or obvious.

1.  Within the Recipe node editor/creator change from "Job Node" to "Job Type Nodes"

2. In the Strikes creation form change label from "Recipe" to "Recipe Type"

3. Workspace status should default to active

There were also so places that might need a tooltip or another indication what exactly it is wanting. 

1. In Workspace what is a Base URL

2. In Strikes make it more obvious they are expecting an input under workspace

3. In Strikes what is a Transfer Suffix

**Comment by ericsvendsen-mil** [comment]
Merged in the changes made so far. If you find any more, go ahead and open a new PR.
