### ISSUE TITLE
Jobs List Time Filter Doesn't Update

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale-ui#162]
The date range picker for the Jobs table defaults to the last 24 hours as of the current time when first loading the page. This time does not seem to update after subsequent loads of the Jobs table causing the results to be filtered off an old time field. Unless a custom date/time has been selected, the date/time picker should be kept up to date with the current time every time the page is re-loaded or re-navigated to.

**Comment by ericsvendsen-mil** [comment]
* Remove time from date input fields
* Change duration buttons to 1, 6, and 12 hour lengths, and make them selectable like radio buttons so the one that is selected is highlighted
* When a duration button is selected, add the duration ISO value as a URL param. When that param is present, then the component will have to use that duration value to determine the start/end dates that will be sent to the API
* If no duration is selected, show results for the current day from 00:00:00 - 23:59:59
* Default to a 1 hour duration
