### ISSUE TITLE
Ingest records page shows only first result

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale-ui#168]
**Description**
When I am using the Ingest Records page I am only seeing a single record, even though the API has returned hundreds.

**Reproduction Steps**
Steps to reproduce the problem:
1. With a fresh Scale DB, I perform the following commands:
```
wget https://github.com/ngageoint/scale/blob/issue-1669/tests/postman/environment.json
https://github.com/ngageoint/scale/blob/issue-1669/tests/postman/full-host-test.json
newman run -k -e environment.json full-host-test.json
```
1. In the Scale UI navigate to Ingest Records: https://scale.omega.aisohio.net/data/ingest
1. I only see 1 record when the API returned 338. See attached screenshot.

**Expected behavior**
I expected to see 20 records as determined by the selected page size in the UI.

**Screenshots**
Ingest Records page where problem is occurring:

![image](https://user-images.githubusercontent.com/4768496/60546844-32341600-9cec-11e9-8d37-8fddaaac4cca.png)

**Version and Environment Details**
 - OS: OSX Mojave 10.14.5
 - Browser: Chromium 75.0.3770.100
 - Scale API:  v6.9.0-snapshot+1d15ca7e
 - Scale UI: v0.4.3

**Comment by ericsvendsen-mil** [comment]
Tried this locally and on dev and have been unable to reproduce this bug. Feel free to reopen if necessary.

**Comment by mikenholt** [comment]
I am seeing this behavior in Omega cluster: 
![Screenshot 2019-07-11 14 24 04](https://user-images.githubusercontent.com/22593495/61075298-a60aa880-a3e7-11e9-9ffb-282d848ffe20.png)
