### ISSUE TITLE
Recipe Type Editing

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#169]
* Add indicator for empty input connection.
* Bug in removing input connection once added (recipe graph component line 636)
* make it obvious that recipe inputs are necessary prior to adding input connections
* add warning if you navigate away without saving

**Comment by mikenholt** [comment]
When the UI submits a recipe for validation it contains an additional property under `my_condition_node[node_type][data_filter]` called `filters_display`.  That needs to be removed before submitting to the backend API.

**Comment by mikenholt** [comment]
For conditional nodes, `node_type[data_filter][filters]` should only contain:
 - name
 - type
 - condition
 - values
![Screenshot 2019-07-03 15 09 41](https://user-images.githubusercontent.com/22593495/60618729-f315cb80-9da4-11e9-9912-f967877b2ca7.png)

**Comment by mikenholt** [comment]
For conditional nodes: `node_type[interface][files][multiple]` must be a boolean.  In my testing I noticed it was set to `null`.

**Comment by mikenholt** [comment]
For conditional nodes: I noticed an additional property of `name` under `node_type` that should be removed before sending to the backend API.

**Comment by mikenholt** [comment]
For conditional nodes: Under `node_type[interface][data_filter][filters]` the property `fields` must be omitted unless it has contents before sending to the backend API.

**Comment by mikenholt** [comment]
Not sure if unrelated: A valid (per the backend validators...) does not display in the UI: 
<img width="1654" alt="Screenshot 2019-07-03 15 28 58" src="https://user-images.githubusercontent.com/22593495/60619794-6a4c5f00-9da7-11e9-99cd-5f39656c0226.png">

JSON for recipe_type: 
```
{
   "name":"hjkjghlhlgghvghk",
   "title":"hjkjghlhlgghvghk",
   "definition":{
      "input":{
         "files":[
            {
               "name":"input_file",
               "required":true,
               "media_types":[
                  "application/octet-stream"
               ],
               "multiple":false
            }
         ],
         "json":[

         ]
      },
      "nodes":{
         "flip-image":{
            "dependencies":[

            ],
            "input":{
               "INPUT_FILE":{
                  "type":"recipe",
                  "input":"input_file"
               }
            },
            "node_type":{
               "node_type":"job",
               "job_type_name":"flip-image",
               "job_type_version":"1.0.0",
               "job_type_revision":1
            }
         },
         "grayscale-image":{
            "dependencies":[
               {
                  "name":"file_name_check",
                  "acceptance":true
               }
            ],
            "input":{
               "INPUT_FILE":{
                  "type":"dependency",
                  "node":"file_name_check",
                  "output":"flipped_image"
               }
            },
            "node_type":{
               "node_type":"job",
               "job_type_name":"grayscale-image",
               "job_type_version":"1.0.0",
               "job_type_revision":1
            }
         },
         "file_name_check":{
            "dependencies":[
               {
                  "name":"flip-image",
                  "acceptance":false
               }
            ],
            "input":{
               "flipped_image":{
                  "node":"flip-image",
                  "output":"flipped_image",
                  "type":"dependency"
               }
            },
            "node_type":{
               "node_type":"condition",
               "interface":{
                  "files":[
                     {
                        "name":"flipped_image",
                        "required":true,
                        "media_types":[
                           "application/octet-stream"
                        ],
                        "multiple":false
                     }
                  ],
                  "json":[]
               },
               "data_filter":{
                  "filters":[
                     {
                        "name":"input_file",
                        "type":"filename",
                        "condition":"==",
                        "values":[
                           "flipped_test.jpg"
                        ],
                        "all_fields":false,
                        "all_files":false
                     }
                  ],
                  "all":true
               }
            }
         }
      }
   }
}
```

**Comment by JohnPTobe** [comment]
Adding an input connection adds it to all inputs for a job node.

**Comment by emimaesmith** [comment]
The hamburger menu still contains 'Validate', 'Save', and 'Cancel' after you save a recipe type. Clicking 'Cancel' takes you back to the edit screen.

**Comment by mheppner** [comment]
Adding a conditional node as a dependency to "scale delete files" results in an error:
```
ERROR TypeError: Cannot read property 'files' of undefined
    at RecipeGraphComponent.push../src/app/common/components/recipe-graph/component.ts.RecipeGraphComponent.addDependency (component.ts:390)
    at Object.eval [as handleEvent] (RecipeGraphComponent.html:328)
```

JobType structure:
```
manifest:
  job:
    interface:
      inputs:
        json: array()
```

**Comment by JohnPTobe** [comment]
Can't remove inactive jobs from recipe since they aren't in the job list. It'd be helpful to just be able to delete a node with an x button or something.

**Comment by JohnPTobe** [comment]
Also, I created issue #206 that I probably should have just put here for the start node bug

**Comment by mheppner** [comment]
Finally figured out Mike's last issue above...the conditional node does not have a name. Need to dig into why this happens.

**Comment by emimaesmith** [comment]
Existing Job Types in a recipe aren't recognized as part of the recipe type when opening the Add/Remove Job Type Nodes dialog. Selecting a job type from this list that is already a part of the recipe type will 'refresh' the node and reset all previously defined connections. This also means removing a job type from a recipe type requires two clicks in the Add/Remove Job Type Nodes dialog.

**Comment by mheppner** [comment]
See PR #211 for full breakdown of everything mentioned in this issue.

Closing in favor of new issues: #186, #206, #216, #217, #218.
