### ISSUE TITLE
Validate/save after editing JSON job type is confusing

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#170]
To make JSON changes to a job-type
Open job-type
Click edit,
Click JSON button
Make changes to text
Click JSON button AGAIN to close,
Then validate.  (Via hamburger menu or step 4)
Then click step 4.
Then click "Edit" button

For discussion: 
Streamline the process considerably with:
Change the "JSON button AGAIN to close" to a "validate" ; and add a "revert/abandon/cancel" button.
Then change the hamburger menu AND step-4 button to include both "save" and add a "revert/abandon/cancel" changes.

That way we get a validation when they're done editing JSON.  And the user has two intuitive ways to save.  Hamburger menu, or move to bottom of step 4 and save.

**Comment by ericsvendsen-mil** [comment]
Added this as a comment to #128
