### ISSUE TITLE
Filtering Lists While On Page Other Than 1 Returns 404 Not Found

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale-ui#175]
**Description**
Selecting a filter when viewing the jobs or recipes list on any page other than 1 returns a 404 Not Found error.

**Reproduction Steps**
Steps to reproduce the problem on the Jobs List page:
1. Navigate to the Jobs list page (Processing -> Jobs from the toolbar)
2. Select page 2
3. Select `Completed` from the Status column and observe the error popup describing a 404 Not Found error for the given url.

Steps to reproduce the problem on the Recipes List page:
1. Navigate to the Recipes list page (Processing -> Recipes from the toolbar)
2. Select page 2
3. Select a specific recipe type from the Recipe Type column drop down and observe the error popup describing a 404 Not Found error for the given url.

**Version and Environment Details**
- OS: Windows 10
- Browser: Google Chrome 71.0.3578.98
- Scale API v7.0.0rc3
- Scale UI: v0.4.3

**Comment by ericsvendsen-mil** [comment]
Resetting the page number to 1 when updating page filters should fix this problem
