### ISSUE TITLE
add warning if you navigate away without saving

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#186]
For the entire application add warning if you navigate away from a form/input without saving.

**Comment by ericsvendsen-mil** [comment]
These two replies to a question on SO seem to provide a good roadmap for this:
* https://stackoverflow.com/a/41187919
* https://stackoverflow.com/a/42108319
Let's use the PrimeNG confirmation component instead of the standard javascript `confirm` though.
