### ISSUE TITLE
Upgrade to Font Awesome 5

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale-ui#187]
Use the cheatsheet to create a new JSON file that can be used for job type icons: https://fontawesome.com/cheatsheet

**Comment by emimaesmith** [comment]
Font Awesome 4 is essentially identical to the free tier of Font Awesome 5. FA4 is currently adequate for our needs and the upgrade to FA5 would introduce more headache than it's worth at this time. Closing due to OBE.
