### ISSUE TITLE
Recipe conditions should be editable.

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#190]
Doesn't appear to be a way to edit an existing condition.  Can only delete them.  --which is also confusing because you have to click the + to add a new condition to get to the page where you can remove a condition.

**Comment by ericsvendsen-mil** [comment]
Discussed this with Chris, and one idea we came up with would be to simply be able to add/edit conditions by name only. Then configure the condition's filter similar to how inputs are managed for job type nodes. This allows the user to quickly add and place a condition within a recipe type, and then specific filter `name` possibilities could be suggested to the user based on the condition's dependencies.
