### ISSUE TITLE
Remove Recipe Type Name

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#191]
The rest api doesn't take a name field and creates a name from the title.  Users only need to give a title for their recipe.

**Comment by ericsvendsen-mil** [comment]
Sorry, but I'm a little confused by this issue. Below are my questions/comments, but we can definitely talk more about this in case I'm completely off base here:

* When you say "Users only need to give a name for their recipe", did you mean to say they only need to give a title?
* Either way, the name field is needed in the front end model for various things like keeping track of recipe type nodes. Also it is a required field when validating a recipe type: http://ngageoint.github.io/scale/docs/rest/v6/recipe_type.html#v6-validate-recipe-type
* The name property is not used when creating or editing a recipe type - only `title`, `description`, and `definition` are sent to the API: https://github.com/ngageoint/scale-ui/blob/master/projects/developer/src/app/configuration/recipe-types/api.model.ts#L70

**Comment by JohnPTobe** [comment]
Oops, yeah I meant title. As for validation, the name field is optional. It's only used when updating an existing recipe type and generating a diff between the old version and the new version.  My apologies for the documentation being crap here, more so than usual.  The main pain point is that users are typing the same thing twice seemingly needlessly.  Perhaps you can use your own unique name behind the scenes? Or have the name field be uneditable and automatically generated from the title?

**Comment by JohnPTobe** [comment]
This is related to https://github.com/ngageoint/scale/issues/1710 btw.

**Comment by ericsvendsen-mil** [comment]
So is there a form in the UI somewhere that asks for or displays the recipe type name? There's been so much going on that it's totally possible that I'm missing it, but the recipe type create/edit form only asks for a title.

**Comment by ericsvendsen-mil** [comment]
Closing for now
