### ISSUE TITLE
Increase SVG skew on publisher job to 45degrees.

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#194]

**Comment by ericsvendsen-mil** [comment]
Not sure if this is technically 45 degrees, but anything more than this would be too much (in my opinion).
![image](https://user-images.githubusercontent.com/15909071/61166236-8ca55180-a4f8-11e9-87d7-61d052a6c6e4.png)

**Comment by cshamis** [comment]
That is perfect.
