### ISSUE TITLE
Fix HTTPS backend for Silo resulting in 503

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale-ui#199]
When a silo backend is being proxied via the nginx servier in a deployment, all requests are failing with a 503 Server Error. This problem is a result of SNI... the solution described here fixes the problem:

https://stackoverflow.com/questions/38931468/nginx-reverse-proxy-error14077438ssl-ssl-do-handshake-failed

**Comment by mheppner** [comment]
Confirmed with Jonathan that this probably isn't needed anymore.
