### ISSUE TITLE
Add a way to manually import a seed image

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale-ui#205]
Where a user wants to import a seed image into Scale that is not hosted in a Silo instance:

* Add "Auto/Manual" switch to step 1 of job type create/edit
* When in manual mode, add a file input that will allow the user to select JSON from the local filesystem. Take the manifest from the selected JSON and add it to the job type definition
* Also add a text input so the user can specify the `docker_image_url` property, since that cannot be determined automatically from the Seed image JSON

**Comment by Rachel-ais** [comment]
fixed in #362
