### ISSUE TITLE
Start Node Not Defined

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#206]
**Description**
When trying to create a recipe, I get an error stating "Node 'Start' is not defined" and am unable to create the recipe.

**Reproduction Steps**
Steps to reproduce the problem:
1. Go to configuration/recipe types in ui
2. Click on the plus button
3. Add job and condition nodes
4. Delete all nodes (besides start which cannot be deleted)
5. Add new job and condition nodes
6. Click Validate and Save from hamburger menu

**Expected behavior**
Recipe should be successfully created.

**Screenshots**
Available on high side.

**Configuration Files**
Available on high side.

**Version and Environment Details**
N/A

**Additional context**

**Comment by emimaesmith** [comment]
I was able to re-produce this error. Looks like it's an issue when adding condition nodes as the first node in the recipe where the UI does not produce the proper node definition:
```
'nodes': {
   'condition_node': {
      'dependencies': [],
      'input': {},
      'node_type': {
         'node_type': 'condition', 
         'interface': {'files': [], 'json': []},
         'data_filter': {
             'filters': [{'name': 'param', 'type': 'boolean', 'condition': '==', 'values': ['True']}],
            'all': true,
         },
   },
   'job_a': {
      'dependencies': [{'name': 'condition_node', 'acceptance': true}].
      'input': {
         'input_file': {'type': 'dependency', 'node': 'Start', 'output': 'input_file'},
      },
      'node_type': {
         'node_type': 'job',
         'job_type_name': 'job_a',
         'job_type_version': '1.0.0',
         'job_type_revision': 1
      }
   }
}
```

Steps to reproduce:
Open the recipe type creation page and open the developer tools to the network tab
1. Create a new Recipe Type, fill in the Title and description
2. Define an input file to the recipe type
3. Create a new condition node 
4. Add a job type and set the dependency to the condition node
5. Click Validate
6. Inspect the validation/ call and note the Request Payload

**Comment by emimaesmith** [comment]
Testing the above steps using UI 0.8.4 does not reproduce this error. Setting it to fixed unless we run into it again.
