### ISSUE TITLE
Make links openable in separate tabs

### ISSUE THREAD

**Issue by wong-j** [ngageoint/scale-ui#215]
Currently unable to open jobs/recipes in separate tabs (i.e. middle-click).  This makes it difficult to view many jobs quickly.

**Comment by ericsvendsen-mil** [comment]
Sorry @mheppner - I know you self-assigned this issue but I can't in good conscience walk away without delivering separate tab functionality for @wong-j. I think he's only been waiting on this for 4 years :-/

I'll submit the PR and let you merge it in.
