### ISSUE TITLE
Inputs are added to all available slots for jobs in recipe graph

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale-ui#217]
[Original comment](https://github.com/ngageoint/scale-ui/issues/169#issuecomment-510560293)

1. Create a new recipe
2. Add a file input, any content
3. Add a job node that has multiple slots for inputs
4. Add your created file input to one of the slots - it ends up populating for all available slots

**Comment by emimaesmith** [comment]
Closed via #347
