### ISSUE TITLE
Fix pause scheduler action

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale-ui#227]
The pause scheduler action does not work. The payload that is sent is: 
```
{"params":{"updates":null,"cloneFrom":null,"encoder":{},"map":{}}}
```

This is is incorrect. The payload should adhere to http://ngageoint.github.io/scale/docs/rest/v6/scheduler.html#v6-update-scheduler

**Comment by Rachel-ais** [comment]
Not obvious when the scheduler button is paused

**Comment by cshamis** [comment]
The nominal state is running.

It should be obvious when paused. Preferably with an error-color and some kind of "pulse" to catch the eye.  Similar to the throbbing indicators on running jobs.
