### ISSUE TITLE
Nice to have: Show system time on front page

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale-ui#230]
Would be nice to see what time the system things it is somewhere on the front page of scale.

**Comment by cshamis** [comment]
Seriously?  You want a clock?  This isn't emacs you know.

**Comment by mikenholt** [comment]
Talk to Jared 😆

**Comment by Nikkala-AIS** [comment]
It was decided that it would take a lot of work to see the system time on the agent running the scheduler and that this feature isn't necessary.
