### ISSUE TITLE
Seed Images dependency

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale-ui#243]
We need to move the Scale UI to consume the new `@ngageoint/seed-images` packages instead of `seed-images`. The previous one was owned by Eric's personal NPM account. 

https://www.npmjs.com/package/@ngageoint/seed-images

**Comment by mikenholt** [comment]
@gisjedi what do you need with this?

**Comment by gisjedi** [comment]
Resolved in https://github.com/ngageoint/scale-ui/pull/362
