### ISSUE TITLE
Prioritize failures in job types history page

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale-ui#253]
From Jonathan: The job type history page was confusing since it showed 0 failures, despite the API returning job failures. Since the page is sorted by primary key, the failures got lost.

Can we prioritize job failures in some way (sort by failed percentage over past 24/48 hrs)?

**Comment by mikenholt** [comment]
We need to investigate this using a real Scale deploy.  It appears to be working with mock data.

**Comment by mikenholt** [comment]
Observations from dev:
- the 24 and 48 hour columns never show results, they must not be getting serialized and binned properly. 
- If more than 1 job is selected the the counts get thrown off

**Comment by emimaesmith** [comment]
Fixed via #342
