### ISSUE TITLE
Batch supersedes check box

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale-ui#273]
Add a `supersedes` checkbox (default to true/checked) to the Batch creation page that indicates to the user if the batch should supersede previous jobs. 

We should probably add a tooltip that explains what it means..... 

Relevant `/v6/batches/` POST payload:
```
{
   "title": "My Batch",
   "description": "My Batch Description",
   "recipe_type_id": 208,
   "supersedes": True,
   "definition": {
      "dataset": 1,
      "forced_nodes": {
         "all": True
      }
   },
   "configuration": {
      "priority": 100
   }
}
```

**Comment by cshamis** [comment]
Yes.  Supercede products, or "fork" a new history.

That is correct idea.

**Comment by emimaesmith** [comment]
This appears to be taken care of by the "Reprocess recipe"/"Create new recipe" radio buttons on the batch creation page.
