### ISSUE TITLE
Datasets page

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale-ui#274]
We need a page in the UI that allows for the creation of datasets. 

Top level thoughts on functionality: 
- List all ScaleFiles with filters that allow it to be whittled down
- Allow for the filtered list to be bundled into a dataset
- Should this UI page also be where we can view details about any file?
- Can we integrate the dataset creation into the Batch create page, or should they remain separate?

**Comment by cshamis** [comment]
For 7.0x   My opinion is make a simple way to create, and build into the batch.

It can be based off an existing batch, or based off recipes that have already run, picked by ingest time or data time.  

In future, we can create a more robust data set creator.

My $.02

**Comment by mheppner** [comment]
Closing, since the ability to create datasets is now in the batches UI. With #434
