### ISSUE TITLE
Scale Metrics not returning any data to the graph

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#281]
When I am choosing metrics to plot there is no data being returned.  A quick check with Jonathan Meyer looks like the back end is sending the messages, but something on the front end is not matching up properly.  
Using Chrome, Scale UI v 7.0 and Scale API 7.0.1 rc3 (I think) in the Dev environment on site

Steps to repeat the test:
1. Choose date 7-1 through current date 8-29
2. Select Job Types from the Data Source drop-down.
3. Choose All Recipes (8 available in Dev)
4. Primary Metric- Completed Count
5. Click Update Chart
Nothing displays
5. Changed Primary Metric to Job Task Time (Avg)
7. Click Update Chart
Nothing Displays
6. Chose Data Source- Errors
7. Selected All (27) from the Name, Category field
8. Select Primary Metric- total Count
9. Click Update Chart
Nothing displays
9. Choose Ingests from the Data Source drop-down
10. Selected all options (3) from the Name drop-down
11. Primary Metric- Average Ingest Time
12. Click Update Chart
Nothing Displays

**Comment by emimaesmith** [comment]
The data coming back from the /api/v6/plot-data request contains values using the new `datetime` instead of `date`. I suspect this isn't being handled properly by the UI as the only place (I am aware of) we were looking to update when the metrics API was updated was the dashboard.

Sample JSON coming back from the API for the call to retrieve the metrics:
```
{
   "count": 4,
    "next": null,
    "previous": null,
    "results": [{
        "column": {
            "name": "total_count",
           "title": "Total Count",
           "description": "Number of completed, failed, and canceled jobs.",
           "units": "count",
           "group": "overview",
           "aggregate": "sum"
        },
        "min_x": "2019-07-31T00:00:00Z",
        "max_x": "2019-08-20T00:00:00Z",
        "min_y": 11,
        "max_y": 3045,
        "values":[{"datetime": "2019-07-31T00:00:00Z", "value": 1},{"datetime": "2019-07-31T00:00:00Z", "value": 0},
```

**Comment by emimaesmith** [comment]
Documenting the charts that need to be updated in #322. Closing this as reverting the Metrics API fixes the immediate problem.
