### ISSUE TITLE
Job Type History View Not Populating when only one choice is selected

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#283]
Using Chrome, Scale UI v 7.0 and Scale API 7.0.1 rc3 (I think) in the Dev environment on site

When a user selects only one job type from the drop down in job type history nothing populates in the table. 

Test Case:
1. Go to Job Type History
2. Select Scale Ingest 1.0.0 as the Job Type
No population of metrics
3. Select another Job Type you know has metrics
Both populate
4. Deselect Scale Ingest 1.0.0
No population of Metrics

**Comment by Rachel-ais** [comment]
Fairly sure this is an API issue but needs more research.

**Comment by emimaesmith** [comment]
PR for API fix located [here](https://github.com/ngageoint/scale/pull/1793).
