### ISSUE TITLE
Ux: Job Status Colors are not clear in dashboard donuts

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#285]
Using Chrome, Scale UI v 7.0 and Scale API 7.0.1 rc3 (I think) in the Dev environment on site

I'm not sure what colors mean under Job Status on the dashboard.  When I hover over Red it says "Algorithm: 1554"  Is this the algorithm's number? or, is this the # of failed something?
Algorithm: 1554 doesn't tie to any other display on the dashboard. 

To replicate use CB...in Dev environment on site which has failed and successful jobs. Make it a favorite.

**Comment by cshamis** [comment]
Likely it means 1554 errors of type (algorithm) for this period.

Scale recognizes 4 types of exit codes. 

Sucesss 
System error <= these should NEVER happen
Algorithm error <= algorithm choked
Data error <= data is bad or non comformant

**Comment by Rachel-ais** [comment]
With the newest Dashboard I think this issue is no longer needed
