### ISSUE TITLE
Ux: Add Label to Date/Time pickers

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#297]
It isn't obvious what time column is the column the date/time pickers are using.  Recommend adding a label saying it was the last modified time.

**Comment by cshamis** [comment]
Good point

**Comment by Nikkala-AIS** [comment]
Sara's main concern was with the Ingest Records view (see issue #303) and she has indicated that adding the "Last Modified" column in that view is sufficient to fix the issue and no universal label is required.
