### ISSUE TITLE
Ux: Suggested new view of times columns

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#300]
I recommend after 24 hours that we change to a date...it's confusing to have "a week ago" or "a month ago".

**Comment by cshamis** [comment]
I disagree.  The dates are there if somebody needs to find then, but the human readable format is easier to grok.

**Comment by mheppner** [comment]
Closing due to customer feedback. Full timestamps are available as tooltips when hovering over the human-friendly text.
