### ISSUE TITLE
Limit recipe type description to 500 characters

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale-ui#312]

**Comment by emimaesmith** [comment]
Related - any field that enforces a character limit in the API should also be limited. 

This currently includes:
- Recipe Type Description
- Scan Description
- Strike Description
- Workspace Description

Future additions:
- Batches Description
- Dataset Description

**Comment by cshamis** [comment]
Postgres doesn't care right?  I mean, we used type TEXT not VARCHARS(xxx) for columns right?  
I mean, somebody will blow up their buffers before they ever hurt the database.  But I guess if we have to, we could always cap it at 1MB.
