### ISSUE TITLE
Update Charts When Metrics API is Updated

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale-ui#322]
When the metrics API is updated to bin the data by hour instead of by day, the following charts need to be updated:

- Dashboard charts
- Metrics pages
- Data Feed

Related to #281

**Comment by cshamis** [comment]
Not all mtrics need to be by the hour.  Except for if they are on the dashboard... but dashboard also needs to support "live" information for the current hour.  ---But ONLY for the dashboard... not every metric we do!

That make sense?
