### ISSUE TITLE
Unschedulable Job Types

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#33]
I added an issue in Scale to add warnings for when there are job types that cannot be scheduled (https://github.com/ngageoint/scale/issues/1492).  Job types that cannot be scheduled will have is_paused set to true or will have a new property set called unmet_resources.  It would be helpful to alert users in some way that there are queued jobs that will never be scheduled.  This could be done on the queue page, in the job table, the dashboard or wherever it makes sense in the new UI.

**Comment by ericsvendsen** [comment]
Is the `unmet_resources` property going to be made available in the `job_type` payload for the following endpoints?

* http://ngageoint.github.io/scale/docs/rest/v6/queue.html#v6-queue-status
* http://ngageoint.github.io/scale/docs/rest/v6/job.html#v6-job-list

**Comment by JohnPTobe** [comment]
Currently no as they both use the base serializer.  Would is_paused be helpful as well?

**Comment by JohnPTobe** [comment]
I can add both of those fields into the base serializer pretty easily. Just a matter of updating docs.  Anything else you can think of that would be helpful for the queue/jobs pages?

**Comment by ericsvendsen** [comment]
I suppose I could see the usefulness of displaying the paused status of the job type. Nothing else besides those two fields comes to mind right now though. Thanks!

**Comment by JohnPTobe** [comment]
Done and waiting for PR approval.  https://github.com/ngageoint/scale/issues/1528
