### ISSUE TITLE
Optional JSON input for jobs

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#333]
If a job has optional JSON input and you add it to a recipe, the recipe will never validate because the JSON being sent back looks like:
{
   "nodes": {
      "json-input": {
           "input": {
                 "INPUT_FILE": {"input": "INPUT_FILE", "type": "recipe"}, "JSON_INPUT": {}
           }
...
the empty {} isn't allowed for that JSON_INPUT. So if no input is defined for that value, it shouldn't be added to the definition. 

This also allows JSON inputs to be connected through the UI

**Comment by emimaesmith** [comment]
Closed via #347
