### ISSUE TITLE
Wrong Node Deprecated

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#336]
When deprecating a node with the ui, the wrong node gets deprecated.  I suspect this is because it's using the index from the status array as the node id in the api call.  When testing, deprecating a node actually deprecated the one before it in the list.  Need to check the pause button works as expected as well.

**Comment by cshamis** [comment]
Computers always start counting at 0.

**Comment by JohnPTobe** [comment]
Unless you’re using a db, matlab, FORTRAN, cobol...

**Comment by emimaesmith** [comment]
Closed via #363
