### ISSUE TITLE
Make UI reflect user privilege

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale-ui#339]
This is a broad issue, but pretty critical to the overall UX of the UI. Presently the UI does not in any way reflect the privilege level of the user. This results in a lot of 403 Forbidden tooltips when users attempt to perform actions for which they do not have authorization to access. A better approach would be to tailor the UI to only show the actions for which the currently logged in user is authorized. In short, the API has 2 levels of privilege:

- All actions that are `GET` operations are allowed by all logged in users. `POST` is also allowed on validation endpoints.
- All actions are allowed to users who have the `is_staff` flag set to true.

The user's profile information can be found at `/api/v7/accounts/profile/`

**Comment by Rachel-ais** [comment]
@gisjedi is this issue still something we need for 7?

**Comment by gisjedi** [comment]
I'd say it's pretty important. Especially if 7 has a long shelf life while working in the next iteration.

**Comment by cshamis** [comment]
Also... 7 will be the only solution for an on-prem SCALE.  Unless we can make a “cloud support in a magic box“  That can provides plug compatible support APIs for all the cloud functions
