### ISSUE TITLE
Automatic Optional Condition

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#343]
It would be handy to automatically create a condition for a user when connecting an optional file output to a required input.  The API allows for a simple test for the existence of a file output by checking if its filename contains the empty string.  If the output exists, this test will pass. If not, the test will fail when it is unable to find a parameter with the given name.

**Comment by cshamis** [comment]
Yes.  Let's capture that for the revamp on conditions slated for 7.1 ot
7.2.

**Comment by mheppner** [comment]
Closing - won't fix since this is a feature request.
