### ISSUE TITLE
Issues From Silo Reported as CORS 

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale-ui#407]
The UI misleadingly reports many issues with silo as CORS issues when that is not always the case. We need to ensure we report when Silo is unavailable (verify is handled correctly in the statuses).

- UI shouldn't say CORS issue when a 503 is returned.
- UI should indicate Silo is unavailable in any case, EXCEPT a true CORS issue.

**Comment by Rachel-ais** [comment]
It seems to work correctly
