### ISSUE TITLE
Jobs table with file inputs

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#414]
Find a way to connect the job with the input. Whether that is with a new data table like Ingest Records or adding an input files column in the jobs table.

**Comment by Rachel-ais** [comment]
This is working but I am individually calling the API to get each of the inputs so we might need to add file inputs into the get all jobs call

**Comment by cshamis** [comment]
Rachel, 

The pie graph with the icons alone just isn’t useful.  

Can you look at this and draw any inspiration?

https://duc.zevv.nl/

**Comment by mheppner** [comment]
Will probably need API changes, since this is making separate requests for each row in the data table.

**Comment by Rachel-ais** [comment]
Api was fixed to handle this in scale [#1860](https://github.com/ngageoint/scale/pull/1860)

Handing it off to Steve
