### ISSUE TITLE
Live range resets table pages

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#418]
When on the jobs table on a different page it will reset when the live range is loaded bringing you back to page 1

**Comment by mheppner** [comment]
I'm not sure of a good way to fix this, and this is an issue for any table that uses the live range, not just the jobs. Say you've filtered the page to showing running jobs and you're on page 20, then all your jobs complete. If the table keeps you on page 20, you'll get a 404 the next time the live range component updates the API. You'll probably be confused, so maybe you go back one page, but you'll keep getting 404s. The API just gives a 404 with message "invalid page."

Some ideas:
1. use the behavior above - let the live range use the current page the user is on, and let the user figure out where to go
2. same as 1, but when an "invalid page" error is encountered, go to page 1
3. same as 2, but first do an initial query to page 1, only to get the available number of pages, then go to the last page
4. modify the API error handler to give us the number of pages available for the "invalid page" error - in the UI, then we would either go to the first or last page available

**Comment by Rachel-ais** [comment]
I agree there's not a good way to fix it. @emimaesmith noticed it this morning and I can see how it would be annoying especially when being reset every 10 seconds.

**Comment by mheppner** [comment]
Closing this in favor of #445.
