### ISSUE TITLE
Metrics (Errors) inconsistent data

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#444]
When selecting the same data it will show them differently:
![Screen Shot 2020-02-26 at 3 22 05 PM](https://user-images.githubusercontent.com/48250701/75384360-f9b10000-58ab-11ea-8589-6660fcc2d43b.png)
For example the data shown for Resource Starvation has data in this graph but not in the next
![Screen Shot 2020-02-26 at 3 22 31 PM](https://user-images.githubusercontent.com/48250701/75384567-501e3e80-58ac-11ea-8070-cacdf7f8e042.png)

**Comment by mheppner** [comment]
Fixed by #446
