### ISSUE TITLE
Simplify date time and live range behavior

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale-ui#445]
After a team discussion regarding the date time pickers and live range dropdowns on various datatables (jobs, recipes, ingest records, scans), this issue is being opened to track the current design and plan how to move forward with a simplified user behavior.

**Desired User Experience:**
If a user navigates to a datatable (ex. Jobs, Recipes, Batches) for the first time, a 24 hour time range of data will display. The user is able to manipulate the time range via the pre-set time ranges (ex. 1 hour, 3 days,etc) or via the calendar date/time option. The date range selection (either the default of 24 hours or the user entry) will be captured in the URL, allowing the user to share the information with another user.  If the user stays on the page and chooses to refresh,the same range would be applied.

- By default, all data tables will display data from the last 24 hours starting with the time the user clicks on the navigation bar option (example, if user clicks on Jobs Data table on 2-27-20 at 2:00 PM the data will be displayed from 2-26-20 2:00PM to 2-27-20 2:00PM)
- The user can manipulate the date range via pre-set ranges or the date/time picker available on the UI.
    - Pre-Set Date Ranges Include: last hour, last 6 hours, last 12 hours, last day, last 3 days, and last week
    - Date/Time picker will allow user to choose a beginning/end date and time (hours and minutes) in UTC
    - Users can choose no end date, or a date in the future, which will allow the data to display new data coming in, with a manual refresh.
- The data will not refresh while the user is on the page unless the user manually refreshes, has chosen no end date in the date/time picker, or has chosen a date in the future (2c)
- The date/time range (either default or user set) will be captured in the URL, allowing the user to share the URL with other Scale users.
- If the user navigates away from the data table and returns, the data tables will reset to the default 24 hour time range.

**Current capabilities:**
- if navigating to a page for the first time, the last 24 hours is selected
- whenever a time range or table header filters are applied, the URL is updated to allow you to share your view with another user
    - (from the first bullet) if you navigate to the page without any filters selected, an internal redirect happens with some defaults set (eg the 24 hours)
    - from home (/) by clicking jobs in the navbar (/jobs), an internal redirect happens that applies the filters (/jobs?started=X&ended=Y)
    - this is not the long-lived persistence discussed below: this behavior will happen in a fresh browser
- live range provides you a 10 second auto refresh using a <last N> selected range
- navigating between data tables persists either your static range or the live range
    - eg, going from jobs to recipes, the same date filter is applied
    - also going from home (/) to jobs (/jobs) will persist the static or live ranges
    - this is long-lived persistence, except for when you clear your browser cache, use private browsing, or change browsers

**Pain points:**
- confusing
- too much persistence
    - if you're on the home page and see 500 jobs currently running, then navigate to the jobs table, you may be confused by not seeing the correct jobs running (if you've previously visited any data table, your start/end date are persisted)
    - if you had previously narrowed down the jobs table to a specific range (Jan 1 - 31), then came back to it six months later to check the running jobs on the cluster, you'd think nothing is currently running (it's not immediately obvious a range from the past is already saved)
- live range is incorrectly named - it isn't a live stream
    - if your system is processing 1k jobs per second, you only see the first 20 on page 1
- Unable to navigate through pages with live range (#418)

**What changes we should consider making:**

- keep the URL-based persistence: allows sharing the current view
    - user story: as a user, I can share with other users the current filters I've applied to the jobs table so they can see exactly what I see
    - existing behavior
- keep the default of 24 hours: navigating to the naked URL (/jobs) should keep the 24 hour redirect
    - user story: as a user, I can see the most recent jobs when navigating to the jobs table for the first time
    - existing behavior, just without the hidden, long-lived persistence
- remove live range
     - no need for a separate control, due to next two bullet points
- remove requirement on end date and add a refresh button: nothing stopping someone from selecting no end date (or even a date for the year 3000), in order to keep refreshing the table to see "live results"
    - user story: as a user, I can click a refresh button to fetch the latest jobs
    - new button for refresh (just requeries the API with existing filters applied)
- add convenience buttons (or in a drop down) to reset the start/end date to last X timeframe
    - user story: as a user, I can click buttons for last hour, last 6 hours, last 12 hours, last day, or last week to view the latest jobs
    - new dropdown or series of buttons for <last N>, which will populate the start/end range (and URL params) using current time -> combined with refresh button will achieve "live range" functionality
- add labels for date time boxes to clarify they are already in UTC
    - also when opening the calendar with null selected (blank text field), ensure the time is also displayed in UTC
- *[optional]* remove the time selector from the calendar: when selecting a value in the start field, use 00:00:00, and the end field, use 23:59:59
    - remove just seconds?

**Comment by mheppner** [comment]
@saradarrah is leading the UX discussions for this effort

**Comment by SaraDarrah** [comment]
@cshamis
Could you please take a look at the user experience and the suggested changes to make sure I captured everything?  
A few specific questions for you:
1. If we remove seconds from the choice, we still have to "send" something to the API, I'm assuming this should be 0-59?
2. We talked yesterday about using no time, but I think that the option of time would allow users to further narrow down the data returned and possibly find that job/recipe/batch they are looking for faster.  So, my advice is to keep the time (hours/minutes) but remove the seconds.

**Comment by cshamis** [comment]
Looks good.  I would say:
Kill the live range (it's really not "live range" as much as an "auto-refresh and range")
Fix the time columns pickers to default to 24 hours and start time at 0000 hours, and end-date at 2400 hours.
If the user clicks "refresh" then re-pull the list.
