### ISSUE TITLE
Issues with create dataset in batches UI

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale-ui#461]
Placeholder issue for now - close this or edit it once we figure out what the actual problem(s) are.

From initial testing on site with UI 0.16.0 and API 7dc11676:
- (maybe an API bug?) when selecting "data time" as the filter, 0 results are returned and the table doesn't show up
    - maybe at least show a message or empty data table
    - verify this is working correctly on the API?
- when selecting "ingest time," the API call is made, the data table is populated, but the spinner remains on top of the table
    - I don't have source maps built here, but stack trace is something about "e is null" > recipeTypeOptions > onQueryDataFilesClick

**Comment by mheppner** [comment]
Consider defaulting start/stop times to now - 24 hours.

**Comment by steveb-ais** [comment]
Split this into 3 Issues.
#463 

> - (maybe an API bug?) when selecting "data time" as the filter, 0 results are returned and the table doesn't show up
>     - maybe at least show a message or empty data table
>     - verify this is working correctly on the API?

#464 
> - when selecting "ingest time," the API call is made, the data table is populated, but the spinner remains on top of the table
>     - I don't have source maps built here, but stack trace is something about "e is null" > recipeTypeOptions > onQueryDataFilesClick

#465 
> Consider defaulting start/stop times to now - 24 hours.
