### ISSUE TITLE
Double arrow in recipe editor

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale-ui#474]
From Sara:

> Whenever you add a dependency a double arrow shows up.  To get it to go away you go in and add/remove a node then it corrects.

Reproduction steps are not available.

**Comment by Fizz11** [comment]
to reproduce: 

- go to create recipe page
- add two nodes of any type
- set one node to be dependent on the other
- observe two arrows!

will revert to 1 arrow when adding or removing any additional node
