### ISSUE TITLE
Limit timeline to latest revisions, add option for past revisions

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale-ui#482]
On the timeline view in the filters panel:
- remove the ability to individually select each revision/version
- add a checkbox to show "all revisions/versions"
    - if false (default), only graph the latest revision for the selected recipe/job
    - if true, graph all revisions for the selected recipe/job

Request from Chris after 5/7/20 demo.

**Comment by cshamis** [comment]
Can you Use different colors for different jobs or recipes.  Same color for versions.
