### ISSUE TITLE
Recipe Nodes after Conditions Showing As a Condition Nodes

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale-ui#497]
Scale 7's Processing -> Recipes -> Recipe Detail view shows the recipe graph color coded as to where the recipe is in its processing. If a sub-recipe node is located after a condition, the sub-recipe node is shown as a condition (the diamond) instead of the usual sub-recipe rectangle.

Example:
The following recipe is made of a job -> a condition -> a sub-recipe. It should be shown as:
<img src="https://user-images.githubusercontent.com/29577288/86386461-c9b1a900-bc5f-11ea-8b89-4908aacfe74b.png" width="175" height="300" />

but instead shows up as: 
<img src="https://user-images.githubusercontent.com/29577288/86386406-b272bb80-bc5f-11ea-8922-e54da0587294.png" width="175" height="300" />

I've not verified if this happens with jobs after conditions as well.

**Comment by Nikkala-AIS** [comment]
This issue seems to have resolved itself and is no longer occurring.  I confirmed with Emily.
