### ISSUE TITLE
Dataset Creation within batches page has issues

### ISSUE THREAD

**Issue by Fizz11** [ngageoint/scale-ui#536]
Currently there are a few issues with the dataset creation part of the batches page. 
First, the list of files is limited to 100 items. we either need to set up paging or at the very least display the total results number along with the first 100 items.
Second, there is no way of filtering the files based on file_type. we need a filter to choose file type, either SOURCE or PRODUCT or BOTH.
The files API has recently been updated to allow filtering by filetype by adding the file_type= argument on to the url. leaving the argument off defaults to both file_types.
Finally, when the datasource is created it does not have any files associated with it. this may be due to a bad or incorrect post call on creation.

**Comment by Nikkala-AIS** [comment]
Dataset creation is not working at the moment.  "...is undefined" errors show up in the TypeScript console.
