### ISSUE TITLE
Job Types Undefined

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#60]
The job types on the job type configuration page all have undefined version numbers and report a 404 error when clicked on.

**Comment by ericsvendsen** [comment]
I believe this is because the API it's pointed at right now doesn't have the latest job type updates yet. So the `/job-types/` endpoint still returns a list of what is now the job type name model.

**Comment by ericsvendsen-mil** [comment]
Closing for now. Feel free to reopen if the above is not true
