### ISSUE TITLE
Metrics page shows same values for min and max

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#61]
For stats like min max file size or time duration both values are the same.

**Comment by ericsvendsen-mil** [comment]
Just some background - there was actually no bug here. The confusion resulted from the fact that the data is stacked in the chart. This makes sense when multiple filters are applied (e.g. specific job types or data feeds), but doesn't make any sense when showing aggregate values. Therefore I removed the stacking in that instance and the data displays as expected.
