### ISSUE TITLE
Whose Scale is it anyway

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#62]
We need some easy way for the user to see which scale instance they're using.  (NDAAS, prod, dev, etc).  If a user is interacting with multiple instances it can be easy to get confused and as an example, accidentally cancel a bunch of jobs they don't want to cancel. Maybe an environment variable can get set in the configuration with a name that is displayed in bold colors at the top of each page?

**Comment by ericsvendsen-mil** [comment]
Values for the primary and secondary Scale colors should be added to /`assets/appConfig.json`:
```
primaryColor: '#017cce',
secondaryLightColor: '#5c97bf',
secondaryDarkColor: '#24567f
```
Then in `/app/theme/dark.ts` and `/app/theme/light.ts` those config values would be used:
```
'--scale-primary': environment.primaryColor,
'--scale-secondary-light': environment.secondaryLightColor,
'--scale-secondary-dark': environment.secondaryDarkColor
```
Environment files and `/app/common/services/app-config.service.ts` would also need to be modified.
