### ISSUE TITLE
Add a "gallery" view to configuration -> job types and Recipes

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#63]
Instead of just a drop-down chooser, add (or replace) the drop-down picker with a "grid-gallery" view for all job types and recipes...  Basically a complete re-use of the SEEDVault display mechanism.  

So the user can see all the jobs, on one page.  Maybe we can "stack" multiple versions?

Recipes work the same way, but need to be slightly different look.  (Maybe even a thumbnail of the recipe tree inside the grid?) Not sure the performance, but it might work...

**Comment by ericsvendsen-mil** [comment]
Consensus on this for now is that the number of jobs and recipes in each recipe type will be highlighted on the overview page.

**Comment by ericsvendsen** [comment]
New consensus is to add labels (with names) for each job and recipe node. Jobs will be one color and recipes another.

**Comment by JohnPTobe** [comment]
Here's a sample of the updated api response:
{"count":2,"next":null,"previous":null,"results":[{"id":185,"name":"test-recipe-type-156","title":"Test Recipe Type 174","description":"A sub recipe","is_active":false,"is_system":false,"revision_num":1,"job_types":[{"version":"1.0.0","name":"my-minimum-job"}],"sub_recipe_types":[],"created":"2019-05-03T14:57:38.556852Z","deprecated":null,"last_modified":"2019-05-03T14:57:38.556876Z"},{"id":186,"name":"test-recipe-type-157","title":"My main recipe","description":"Test Description 171","is_active":true,"is_system":true,"revision_num":1,"job_types":[{"version":"0.1.0","name":"test-job-type-266"}],"sub_recipe_types":["test-recipe-type-156"],"created":"2019-05-03T14:57:38.567143Z","deprecated":null,"last_modified":"2019-05-03T14:57:38.567166Z"}]}
