### ISSUE TITLE
Red Fail donuts for Favorites / All Job Types

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#69]
Just showing errors alone sends wrong message.  Need to show in relation to percentage of successes and errors, or find another visualization.

**Comment by ericsvendsen-mil** [comment]
Added counts for completed and running as well as the failed breakdown.
![image](https://user-images.githubusercontent.com/15909071/57118499-b6d8d700-6d31-11e9-8b13-1841ce8066cb.png)

**Comment by cshamis** [comment]
Hmmm... let's Lose the blue (running) jobs?.  Looks like the Obama shield.

**Comment by ericsvendsen** [comment]
Blue is completed. Green is running.

**Comment by ericsvendsen-mil** [comment]
Closed via b60dd78
