### ISSUE TITLE
It's over 1000

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#75]
The v7 nodes page calls the node rest api with a page size of 1000 but we have over 1000 nodes in our production cluster, resulting in some nodes being left out of the ui.

**Comment by JohnPTobe** [comment]
The resolution for this issue might just be to delete some old nodes from the database. We need to discuss it.

**Comment by ericsvendsen-mil** [comment]
Not sure why this is in the UI repo...

**Comment by JohnPTobe** [comment]
The v7 nodes page in the UI leaves out some nodes because it only looks at the first 1000

**Comment by JohnPTobe** [comment]
My mistake, I thought that was just being set in the UI but I see now there is a max of 1000 per page in scale's pagination code.  We could possibly increase that and/or fix our node overflow.

**Comment by ericsvendsen-mil** [comment]
I mean I could introduce pagination to the view, or lazy loading, to get around the 1000 limit. I just know that in the past the preference for this view has been to not have that happen.

**Comment by JohnPTobe** [comment]
Yeah, I'm going to close this issue as we just need to clean up the node table.
