### ISSUE TITLE
Don't show old nodes

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#78]
The nodes page currently shows all the nodes that ever existed in Scale.  This isn't useful as it gives us 900+ deprecated nodes that we don't care about.  We should hide nodes that are not active and offline.

**Comment by ericsvendsen-mil** [comment]
The labels at the top of the nodes view will show/hide the nodes based on each status value. I can certainly make some hidden by default, but what you describe here is basically already available.

**Comment by JohnPTobe** [comment]
In the v5 ui we don't show nodes that are deprecated and offline. That's what I mean.  We only want to see deprecated nodes that are online so we can possibly reactivate them.  I'm ok discussing getting rid of the whole deprecated concept as it causes confusion but the current situation will result in old nodes piling up and the deprecated label will be useless with lots of nodes to sort through that aren't valid.

**Comment by ericsvendsen-mil** [comment]
Oh, so in the old UI? Ok. I'll transfer this issue to the main Scale repo then if that's the case.

**Comment by ericsvendsen-mil** [comment]
Closing this because I believe it has been addressed. Feel free to reopen if necessary.
