### ISSUE TITLE
Dashboard date/time range consistency control

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#82]
Universal switch for dashboard metric charts 

two modes:
1 day in 24 hours interval
7 days at 1 day interval

**Comment by ericsvendsen-mil** [comment]
Can't finish this until metrics results can be binned by the hour in addition to the day.

**Comment by mikenholt** [comment]
**TODO: Leave note about how we will rework the front-page.** 


Additional note from Jared: on the queue depth chart it would be useful to breakout user-queued vs ingest-queued.  This would help differentiate between files coming in and a large batch that just dropped.

**Comment by cshamis** [comment]
Ingest is a system job, so you :could: filter on that.

**Comment by Rachel-ais** [comment]
Closed in #405
