### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#86]
Since scale no longer works with http, we should automatically redirect to https

**Comment by gisjedi** [comment]
This is done here: https://github.com/ngageoint/scale/blob/6528bb28a76c177277f64e2c92d73a5a1e009535/dockerfiles/framework/scale/app-templates/ui.json#L36

If it is deployed via the Scale deploy, it should be done. The only case you could get to it at HTTP would be if it was manually deployed into DCOS or if the DCOS admin console is accessed over HTTP (only possible in < DCOS 1.10).

**Comment by JohnPTobe** [comment]
ok, I was having problems if I didn't specify https yesterday. is this just not set properly on dev and/or kraken?

**Comment by gisjedi** [comment]
Should be resolved via: https://github.com/ngageoint/scale/pull/1681
