### ISSUE TITLE
Show Job Will Not Be Retried

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale-ui#90]
Currently there is no visibility as to which errors will be automatically be retried or not.  It would be helpful to know when looking at a failed job that it was not retried because the error is not retry-able or it has exceeded it's max tries already. Jobs also will not be automatically retried if they are superseded.

**Comment by ericsvendsen-mil** [comment]
Looking through the scale API docs it's not clear to me how to determine when a job has exceeded its max tries. There is a `max_scheduled` property for a Job Type, but that's not really what we're looking for here. Is max tries specified somewhere in the seed manifest?

**Comment by JohnPTobe** [comment]
I thought there was but maybe it’s not shown? For nearly all job types it’s 3 so if the error is not retry-able or it’s at 3 retries it should be flagged somehow. Talk to Chris, maybe just that the error isn’t automatically retried is more important

**Comment by ericsvendsen-mil** [comment]
This has some unanswered API questions

**Comment by JohnPTobe** [comment]
I added an issue for adding the max_tries to the API.  I think the error not being one that is automatically retried is more important but adding that field to the serializers would be trivial.

**Comment by mikenholt** [comment]
Inspect the # of executions and the max_tries.  If they are equal make it obvious that this job will not be retried.

**Comment by mikenholt** [comment]
Add indicator to Jobs table (exclamation point icon or something similar) with hover message and a banner to the Job Details page.

**Comment by cshamis** [comment]
No... don't grey out the button.  Humans can always override.  The not retryable means the automatic retries are exhausted and/or the error is not a retryable error.

A data error is not retryable because it would have the same result.
